### ISSUE TITLE
Expired tokens should give a user the change to make another token

### ISSUE THREAD

**Issue by heetbeet** [AutoActuary/app-builder#11]

**Comment by heetbeet** [comment]
No, I think this is related to expired tokens. Another thing I should fix soon

**Comment by heetbeet** [comment]
```
  File "C:\Users\simon\AppData\Local\autoactuary\app-builder\versions\v0.2.4\repo\app_builder\exec_py.py", line 57, in exec_py
    exec(compile(file.read(), filepath, 'exec'), global_names, local_names)
  File "C:\Users\simon\AppData\Local\autoactuary\app-builder\versions\v0.2.4\repo\app_builder\src-legacy\tools\application.py", line 29, in <module>
    exec_py.exec_py(this_dir().joinpath("..", "deployment-and-release-scripts", "create-github-release.py"), globals())
  File "C:\Users\simon\AppData\Local\autoactuary\app-builder\versions\v0.2.4\repo\app_builder\exec_py.py", line 57, in exec_py
    exec(compile(file.read(), filepath, 'exec'), global_names, local_names)
  File "C:\Users\simon\AppData\Local\autoactuary\app-builder\versions\v0.2.4\repo\app_builder\src-legacy\tools\..\deployment-and-release-scripts\create-github-release.py", line 80, in <module>
    github_release.get_releases(name_repo)
  File "C:\Users\simon\AppData\Local\autoactuary\app-builder\versions\v0.2.4\site-packages\github_release.py", line 249, in get_releases
    _recursive_gh_get(
  File "C:\Users\simon\AppData\Local\autoactuary\app-builder\versions\v0.2.4\site-packages\github_release.py", line 155, in _recursive_gh_get
    response.raise_for_status()
  File "C:\Users\simon\AppData\Local\autoactuary\app-builder\versions\v0.2.4\site-packages\requests\models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.github.com/repos/heetbeet/temporary_git_repository/releases
```

**Comment by heetbeet** [comment]
```
Traceback (most recent call last):
  File "<string>", line 12, in <module>
  File "C:\Users\simon\AppData\Local\autoactuary\app-builder\versions\v0.2.4\repo\app_builder\main.py", line 52, in <module>
    exec_py.exec_py(this_dir().joinpath("src-legacy", "tools", "application.py"), globals())
  File "C:\Users\simon\AppData\Local\autoactuary\app-builder\versions\v0.2.4\repo\app_builder\exec_py.py", line 57, in exec_py
    exec(compile(file.read(), filepath, 'exec'), global_names, local_names)
  File "C:\Users\simon\AppData\Local\autoactuary\app-builder\versions\v0.2.4\repo\app_builder\src-legacy\tools\application.py", line 29, in <module>
    exec_py.exec_py(this_dir().joinpath("..", "deployment-and-release-scripts", "create-github-release.py"), globals())
  File "C:\Users\simon\AppData\Local\autoactuary\app-builder\versions\v0.2.4\repo\app_builder\exec_py.py", line 57, in exec_py
    exec(compile(file.read(), filepath, 'exec'), global_names, local_names)
  File "C:\Users\simon\AppData\Local\autoactuary\app-builder\versions\v0.2.4\repo\app_builder\src-legacy\tools\..\deployment-and-release-scripts\create-github-release.py", line 80, in <module>
    github_release.get_releases(name_repo)
  File "C:\Users\simon\AppData\Local\autoactuary\app-builder\versions\v0.2.4\site-packages\github_release.py", line 249, in get_releases
    _recursive_gh_get(
  File "C:\Users\simon\AppData\Local\autoactuary\app-builder\versions\v0.2.4\site-packages\github_release.py", line 155, in _recursive_gh_get
    response.raise_for_status()
  File "C:\Users\simon\AppData\Local\autoactuary\app-builder\versions\v0.2.4\site-packages\requests\models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.github.com/repos/heetbeet/temporary_git_repository/releases
```
