### ISSUE TITLE
This error message doesn't convey the fact that WinPython x.y.z cannot be found

### ISSUE THREAD

**Issue by heetbeet** [AutoActuary/app-builder#40]
PS C:\Users\simon\devel\chain-ladder> app-builder -l
Traceback (most recent call last):
  File "<string>", line 12, in <module>
  File "C:\Users\simon\AppData\Local\autoactuary\app-builder\versions\v0.3.0\repo\app_builder\main.py", line 52, in <module>
    exec(compile(file.read(), filepath, 'exec'), global_names, local_names)
  File "C:\Users\simon\AppData\Local\autoactuary\app-builder\versions\v0.3.0\repo\app_builder\src-legacy\tools\application.py", line 26, in <module>
    exec_py.exec_py(this_dir().joinpath("..", "deployment-and-release-scripts", "create-releases.py"), globals())
  File "C:\Users\simon\AppData\Local\autoactuary\app-builder\versions\v0.3.0\repo\app_builder\exec_py.py", line 57, in exec_py
    exec(compile(file.read(), filepath, 'exec'), global_names, local_names)
  File "C:\Users\simon\AppData\Local\autoactuary\app-builder\versions\v0.3.0\repo\app_builder\src-legacy\tools\..\deployment-and-release-scripts\create-releases.py", line 338, in <module>
    create_releases()
  File "C:\Users\simon\AppData\Local\autoactuary\app-builder\versions\v0.3.0\repo\app_builder\src-legacy\tools\..\deployment-and-release-scripts\create-releases.py", line 47, in create_releases
    create_dependencies.create_all_dependencies()
  File "C:\Users\simon\AppData\Local\autoactuary\app-builder\versions\v0.3.0\repo\app_builder\src-legacy\deployment-and-release-scripts\create-dependencies.py", line 58, in create_all_dependencies
    misc.get_python(version)
  File "C:\Users\simon\AppData\Local\autoactuary\app-builder\versions\v0.3.0\repo\app_builder\src-legacy\deployment-and-release-scripts\misc.py", line 323, in get_python
    filename = Path(url).name
  File "C:\Users\simon\AppData\Local\autoactuary\app-builder\bin\python\lib\pathlib.py", line 1042, in __new__
    self = cls._from_parts(args, init=False)
  File "C:\Users\simon\AppData\Local\autoactuary\app-builder\bin\python\lib\pathlib.py", line 683, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "C:\Users\simon\AppData\Local\autoactuary\app-builder\bin\python\lib\pathlib.py", line 667, in _parse_args
    a = os.fspath(a)

**Comment by heetbeet** [comment]
This is from a previous mechanism for sourcing Python. It should not occur anymore.
